// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package words

import (
	"easyword/api/words"
	usersLogic "easyword/internal/logic/users"
	wordsLogic "easyword/internal/logic/words"
)

type ControllerV1 struct {
	users *usersLogic.Users
	words *wordsLogic.Words
}

func NewV1() words.IWordsV1 {
	return &ControllerV1{
		users: usersLogic.New(),
		words: wordsLogic.New(),
	}
}
