// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package account

import (
	"easyword/api/account"
	"easyword/internal/logic/users"
)

type ControllerV1 struct {
	users *users.Users
}

func NewV1() account.IAccountV1 {
	return &ControllerV1{
		users: users.New(),
	}
}
