// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package users

import (
	"easyword/api/users"
	userLogic "easyword/internal/logic/users"
)

type ControllerV1 struct {
	users *userLogic.Users
}

func NewV1() users.IUsersV1 {
	return &ControllerV1{
		users: userLogic.New(),
	}
}
